### ISSUE TITLE
Interfering with Live Preview in Brackets 1.1

### ISSUE THREAD

**Issue by StephenESC** [adobe-webplatform/css-shapes-editor#17]
Ever since upgrading to Brackets 1.1, I had been having issues with the Brackets Live Preview where Chrome would launch but then lose the connection. I kept getting the message “Live Preview cancelled for unknown reason {(0)}”.

After a bit of trial and error—removing all extensions and adding them back in on-by-one—it turned out to be Adobe’s CSS Shapes Editor for Brackets extension that was causing the issues. I removed that and everything works fine again.

**Comment by oslego** [comment]
Thanks for spotting. Reported bug in the Brackets CSS Shapes Editor [extension repo](https://github.com/adobe-webplatform/brackets-css-shapes-editor/issues/4#issuecomment-67867192), since that's where the issue is likely to be. Please track that.

Closing this here.
